name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
          sudo apt-get update
          sudo apt-get -y install texlive ttf-mscorefonts-installer tex-common texlive-full texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-xetex pdftk python3 xzdec
      - name: Install pandoc
        run: |
          wget "https://github.com/jgm/pandoc/releases/download/2.19/pandoc-2.19-1-amd64.deb"
          sudo dpkg -i pandoc-2.19-1-amd64.deb
          wget "https://github.com/kprussing/pandoc-acro/archive/afde5ef.zip"
          unzip afde5ef.zip
          cd pandoc-acro-afde5ef6ed58292f75c076455b895344347c94f7
          ls -al
          sudo python setup.py install
          cd ..
      - name: Setup dirs
        run: bash .github/bin/setup.sh
      - name: Build PDFs
        run: bash .github/bin/build.sh
      - name: Upload PDFs
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: "~/build/*"
