name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build PDFs
        run: build.sh
      - name: Copy build files from image
        run: docker cp nakdocker:/build ~
      - name: Upload PDFs
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: "/tmp/build/*"
