name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
          sudo apt-get update
          sudo apt-get -y install texlive ttf-mscorefonts-installer texlive-latex-extra texlive-xetex texlive-bibtex-extra biber pdftk
      - name: Install python
        uses: actions/setup-python@v4 
        with:
          python-version: 'pypy3.9'
      - name: Install pandoc
        run: |
          wget "https://github.com/jgm/pandoc/releases/download/2.19/pandoc-2.19-1-amd64.deb"
          sudo dpkg -i pandoc-2.19-1-amd64.deb
      #- name: Install pandoc-acronyms
      #  run: |
      #    pip install pandoc-acronyms
      #    pip install panflute
      #    export PANDOC_ACRONYMS_ACRONYMS=${{github.workspace}}/${{env.acronyms_file}}/${{env.folder}}/${{env.acronyms_file}}
      # --filter pandoc-acronyms ${{env.md_files}}
      - name: Setup dirs
        working-directory: ${{github.workspace}}
        run: |
           mkdir build
           CONFIGURATIONS=$(find ~+ -type f -name 'config.sh' -exec dirname -z "{}" \; | sed -z 's/$/\n/')
           cd build
           for CONF in $CONFIGURATIONS;
           do
           . ${CONF}/config.sh
           CONF_FOLDER=$(basename ${CONF})
           echo "Creating dir build/${CONF_FOLDER}"
           mkdir ${CONF_FOLDER}
           done
           cd ..
      - name: Build PDFs
        working-directory: ${{github.workspace}}
        run: |
           CONFIGURATIONS=$(find ~+ -type f -name 'config.sh' -exec dirname -z "{}" \; | sed -z 's/$/\n/')
           echo "\printbibliography" >> bib.md
           for CONF in $CONFIGURATIONS;
           do
           . ${CONF}/config.sh
           CONF_FOLDER=$(basename ${CONF})
           for STYLE in ${CONF_STYLES};
           do
           echo ${STYLE}
           cd $CONF
           echo "Build PDF for ${CONF_FOLDER} with ${STYLE}"
           pandoc --from markdown --to=latex --latex-engine=xelatex --embed-resources --standalone --table-of-contents --biblatex --bibliography=${CONF_BIB} --abbreviations=${CONF_ABBREVIATIONS_FILE} --number-sections --metadata-file ../${STYLE} ${CONF_MD_FILES} ../bib.md -o ${STYLE}.tex
           xelatex ${STYLE}.tex
           echo "Combine PDF for ${CONF_FOLDER} with ${STYLE}"
           pdftk ${CONF_COVER} ${STYLE}.pdf cat output ../build/${CONF_FOLDER}/${CONF_FOLDER}_${STYLE}.pdf
           cd ..
           done
           done
      - name: Upload combined PDFs
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: "build/*"
