name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update system
        run: | 
          sudo apt-get upgrade
          sudo apt-get update
      - name: Install python
        run: sudo apt-get -y install python3
      - name: Install pdftk
        run: sudo apt-get -y install pdftk
      - name: Install mscorefonts
        run: | 
          echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
          sudo apt-get -y install ttf-mscorefonts-installer
      - name: Install latex
        run: |
          cd /tmp
          wget https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
          zcat install-tl-unx.tar.gz | tar xf -
          rm -rf install-tl-unx.tar.gz
          cd install-tl-*
          sudo perl ./install-tl --no-interaction
          PATH=$PATH:/usr/local/texlive/2022/bin/x86_64-linux
      - name: Latex version
        run: echo $(latex --version)
      - name: Install latex package acro (requires nicematrix)
        run: |
          wget "https://mirrors.ctan.org/macros/latex/contrib/acro.zip"
          unzip acro
          DIR=$(kpsewhich -var-value=TEXMFHOME)
          mkdir -p ${DIR}/tex/latex/commonstuff/
          cp acro/acro.sty ${DIR}/tex/latex/commonstuff/
      - name: Install latex package nicematrix
        run: |
          wget "https://mirrors.ctan.org/macros/latex/contrib/nicematrix.zip"
          unzip nicematrix
          cd nicematrix
          latex nicematrix.ins
          cd ..
          DIR=$(kpsewhich -var-value=TEXMFHOME)
          mkdir -p ${DIR}/tex/latex/commonstuff/
          cp nicematrix/nicematrix.sty ${DIR}/tex/latex/commonstuff/
      - name: Install pandoc
        run: |
          wget "https://github.com/jgm/pandoc/releases/download/2.19/pandoc-2.19-1-amd64.deb"
          sudo dpkg -i pandoc-2.19-1-amd64.deb
      - name: Install pandoc package pandoc-acro (requires acro)
        run: |
          wget "https://github.com/kprussing/pandoc-acro/archive/afde5ef.zip"
          unzip afde5ef.zip
          cd pandoc-acro-afde5ef6ed58292f75c076455b895344347c94f7
          ls -al
          sudo python setup.py install
          cd ..
      - name: Setup dirs
        run: bash .github/bin/setup.sh
      - name: Build PDFs
        run: bash .github/bin/build.sh
      - name: Upload PDFs
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: "~/build/*"
