name: Build TL1
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:

################################### edit from here ##########################################

      folder: TL1                                                                            # the name of the folder where the 'Transferleistung' is located
      titlepage: titlepage.pdf                                                               # the name of the titlepage (has to be a pdf)
      acronyms_file: acronyms.json                                                           # the name of the acronyms file (has to be json)
      md_files: 0_example.md
#        ^  specifies the order of the markdown files

      styles: style_de_arial.yaml style_de_tnr.yaml style_en_arial.yaml style_en_tnr.yaml    # you should only use one language in this job - choose one (if you want both than create a new folder)

################################### edit to here   ##########################################

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
          sudo apt-get update
          sudo apt-get -y install texlive ttf-mscorefonts-installer texlive-latex-extra texlive-xetex pdftk
      - name: Install python
        uses: actions/setup-python@v4 
        with:
          python-version: 'pypy3.9'
      - name: Install pandoc
        run: |
          wget "https://github.com/jgm/pandoc/releases/download/2.19/pandoc-2.19-1-amd64.deb"
          sudo dpkg -i pandoc-2.19-1-amd64.deb
      #- name: Install pandoc-acronyms
      #  run: |
      #    pip install pandoc-acronyms
      #    pip install panflute
      #    export PANDOC_ACRONYMS_ACRONYMS=${{github.workspace}}/${{env.acronyms_file}}/${{env.folder}}/${{env.acronyms_file}}
      # --filter pandoc-acronyms ${{env.md_files}}
      - name: Build PDFs
        working-directory: ${{github.workspace}}
        run: |
           for STYLE in ${{env.styles}};
           do
           echo ${STYLE}
           cd ${{env.folder}}
           pandoc --from markdown --to=pdf --pdf-engine=xelatex --embed-resources --standalone --citeproc --toc --number-sections --metadata-file ../${STYLE} ${{env.md_files}} -o ${STYLE}.pdf
           cd ..
           done
      - name: Combine PDFs
        run: |
           for STYLE in ${{env.styles}};
           do
           cd ${{env.folder}}
           pdftk ${{env.titlepage}} ${STYLE}.pdf cat output ${{env.folder}}_${STYLE}.pdf
           cd ..
           done
      - name: Upload combined PDFs
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: ${{env.folder}}/${{env.folder}}_*.pdf
