name: Spellchecking (de)
on:
  pull_request:
    branches:
      - 'de-*'
      - '*-de'
      - '*-de-*'
      - 'de_*'
      - '*_de'
      - '*_de_*'

jobs:
  LanguageTool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run LanguageTool with reviewdog
        uses: reviewdog/action-languagetool@v1.8.2
        with:
          language: de-DE
          disabled_categories: ''
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
